<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit15d7ec6dd7fa3de34e1c6a105ac306dd
{
    public static $files = array (
        'c594688b3441835d5575f3085da4a242' => __DIR__ . '/..' . '/webonyx/graphql-php/src/deprecated.php',
    );

    public static $prefixLengthsPsr4 = array (
        'G' => 
        array (
            'GraphQL\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'GraphQL\\' => 
        array (
            0 => __DIR__ . '/..' . '/webonyx/graphql-php/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit15d7ec6dd7fa3de34e1c6a105ac306dd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit15d7ec6dd7fa3de34e1c6a105ac306dd::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
